version: '3.8'

services:
  mfih-lms-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mfih-lms-container
    restart: always
    ports:
      # فقط Nginx لینوکس می‌تواند به این پورت دسترسی داشته باشد (امنیت بالا)
      - "127.0.0.1:3002:3000"
    volumes:
      # ذخیره‌سازی دائمی فایل‌ها روی سرور لینوکس
      - /home/mfih/mfih_LMS/storage:/app/storage
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - STORAGE_PATH=/app/storage
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"