-- ====================================================================================
-- EITAA MINI-APP LMS: COMPREHENSIVE SUPABASE SCHEMA & RLS POLICIES
-- ====================================================================================

-- 1. ENUMS
CREATE TYPE user_role AS ENUM ('student', 'teacher', 'executive_manager', 'finance_admin');
CREATE TYPE lesson_type AS ENUM ('video', 'audio', 'pdf', 'quiz', 'certificate');
CREATE TYPE enrollment_status AS ENUM ('active', 'completed', 'cancelled');
CREATE TYPE transaction_type AS ENUM ('deposit', 'withdrawal', 'purchase', 'payout');
CREATE TYPE transaction_status AS ENUM ('pending', 'completed', 'failed');

-- 2. USERS & PROFILES
-- We extend the default auth.users table using a public profile table.
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  role user_role DEFAULT 'student'::user_role NOT NULL,
  full_name TEXT,
  avatar_url TEXT,
  phone_number TEXT UNIQUE,
  eitaa_id TEXT UNIQUE,           -- Used for invisible Eitaa Mini-App login
  eitaa_username TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. COURSES
CREATE TABLE courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instructor_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT,
  price NUMERIC DEFAULT 0,
  cover_url TEXT,
  is_published BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. CHAPTERS
CREATE TABLE chapters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  order_num INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. LESSONS
CREATE TABLE lessons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chapter_id BIGINT REFERENCES chapters(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  type lesson_type NOT NULL,
  description TEXT,
  duration_minutes INTEGER DEFAULT 0,
  media_url TEXT,
  is_free BOOLEAN DEFAULT FALSE,
  order_num INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. ENROLLMENTS
CREATE TABLE enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
  status enrollment_status DEFAULT 'active'::enrollment_status,
  progress_percent INTEGER DEFAULT 0,
  enrolled_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, course_id)
);

-- 7. USER PROGRESS (Tracking individual lessons)
CREATE TABLE user_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  lesson_id BIGINT REFERENCES lessons(id) ON DELETE CASCADE,
  is_completed BOOLEAN DEFAULT FALSE,
  completed_at TIMESTAMP WITH TIME ZONE,
  UNIQUE(user_id, lesson_id)
);

-- 8. QUIZZES & ASSESSMENTS
-- A quiz is linked to a lesson of type 'quiz'
CREATE TABLE quizzes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id BIGINT REFERENCES lessons(id) ON DELETE CASCADE UNIQUE,
  pass_score INTEGER DEFAULT 50, -- Minimum percentage to pass
  time_limit_minutes INTEGER
);

CREATE TABLE quiz_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id BIGINT REFERENCES quizzes(id) ON DELETE CASCADE,
  question_text TEXT NOT NULL,
  order_num INTEGER DEFAULT 0
);

CREATE TABLE quiz_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT REFERENCES quiz_questions(id) ON DELETE CASCADE,
  option_text TEXT NOT NULL,
  is_correct BOOLEAN DEFAULT FALSE
);

CREATE TABLE quiz_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  quiz_id BIGINT REFERENCES quizzes(id) ON DELETE CASCADE,
  score INTEGER NOT NULL,
  is_passed BOOLEAN NOT NULL,
  submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. WALLET & TRANSACTIONS
CREATE TABLE wallets (
  id UUID REFERENCES profiles(id) ON DELETE CASCADE PRIMARY KEY,
  balance NUMERIC DEFAULT 0 NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id UUID REFERENCES wallets(id) ON DELETE CASCADE,
  course_id BIGINT REFERENCES courses(id) ON DELETE SET NULL, -- Null if not a course purchase (e.g. deposit)
  type transaction_type NOT NULL,
  amount NUMERIC NOT NULL,
  status transaction_status DEFAULT 'pending'::transaction_status,
  reference_id TEXT, -- Payment gateway reference
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ====================================================================================
-- ROW-LEVEL SECURITY (RLS) POLICIES
-- ====================================================================================

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE chapters ENABLE ROW LEVEL SECURITY;
ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

-- Helper Function to check role
CREATE OR REPLACE FUNCTION auth.user_role() RETURNS user_role AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid();
$$ LANGUAGE sql SECURITY DEFINER;

-- Profiles: Users can read their own, Managers can read all
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Managers can view all profiles" ON profiles FOR SELECT USING (auth.user_role() IN ('executive_manager', 'finance_admin'));
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Courses: Everyone can see published. Managers/Teachers can see all and insert/update.
CREATE POLICY "Anyone can view published courses" ON courses FOR SELECT USING (is_published = TRUE);
CREATE POLICY "Managers and Teachers can view all courses" ON courses FOR SELECT USING (auth.user_role() IN ('executive_manager', 'teacher'));
CREATE POLICY "Managers and Teachers can manage courses" ON courses FOR ALL USING (auth.user_role() IN ('executive_manager', 'teacher'));

-- Chapters & Lessons: Viewable if course is published OR user is manager/teacher. Manageable by manager/teacher.
CREATE POLICY "Public read chapters of published courses" ON chapters FOR SELECT USING (EXISTS (SELECT 1 FROM courses WHERE id = chapters.course_id AND is_published = TRUE));
CREATE POLICY "Manage chapters" ON chapters FOR ALL USING (auth.user_role() IN ('executive_manager', 'teacher'));

CREATE POLICY "Public read lessons of published courses" ON lessons FOR SELECT USING (EXISTS (SELECT 1 FROM chapters JOIN courses ON chapters.course_id = courses.id WHERE chapters.id = lessons.chapter_id AND courses.is_published = TRUE));
CREATE POLICY "Manage lessons" ON lessons FOR ALL USING (auth.user_role() IN ('executive_manager', 'teacher'));

-- Enrollments: View own. Managers see all. Manageable by managers.
CREATE POLICY "Users view own enrollments" ON enrollments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Managers view all enrollments" ON enrollments FOR SELECT USING (auth.user_role() = 'executive_manager');
CREATE POLICY "Users can insert own enrollment (free courses / post payment)" ON enrollments FOR INSERT WITH CHECK (auth.uid() = user_id);

-- User Progress: View/Update own.
CREATE POLICY "Users manage own progress" ON user_progress FOR ALL USING (auth.uid() = user_id);

-- Quizzes: Read public. Manage managers/teachers.
CREATE POLICY "Read quizzes" ON quizzes FOR SELECT USING (TRUE);
CREATE POLICY "Manage quizzes" ON quizzes FOR ALL USING (auth.user_role() IN ('executive_manager', 'teacher'));
CREATE POLICY "Read questions" ON quiz_questions FOR SELECT USING (TRUE);
CREATE POLICY "Manage questions" ON quiz_questions FOR ALL USING (auth.user_role() IN ('executive_manager', 'teacher'));
CREATE POLICY "Read options" ON quiz_options FOR SELECT USING (TRUE);
CREATE POLICY "Manage options" ON quiz_options FOR ALL USING (auth.user_role() IN ('executive_manager', 'teacher'));

-- Quiz Results: View own. Insert own.
CREATE POLICY "Users view own quiz results" ON quiz_results FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own quiz results" ON quiz_results FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Managers view all quiz results" ON quiz_results FOR SELECT USING (auth.user_role() IN ('executive_manager', 'teacher'));

-- Wallets & Transactions: View own. Managers see all.
CREATE POLICY "Users view own wallet" ON wallets FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Finance admin views all wallets" ON wallets FOR SELECT USING (auth.user_role() = 'finance_admin');
CREATE POLICY "Users view own transactions" ON transactions FOR SELECT USING (EXISTS (SELECT 1 FROM wallets WHERE id = transactions.wallet_id AND wallets.id = auth.uid()));
CREATE POLICY "Finance admin views all transactions" ON transactions FOR SELECT USING (auth.user_role() = 'finance_admin');

-- Triggers (e.g. creating a wallet on profile creation)
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.wallets (id, balance) VALUES (new.id, 0);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON public.profiles
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
